### ISSUE TITLE
change where the examples sentences appear

### ISSUE THREAD

**Issue by vczEz** [artyompetrov/AutoDefine_oxfordlearnersdictionaries#10]
I think the most useful card for vocabulary minning is:

Field:

1.- Setence
2.- Tarjet word
3.- Definition
4.- Word Audio
5.- Image
6.- Example sentences

you can try move the examples sentences in the field of sentences? if this is hight cost in speed doesn´t change

**Comment by artyompetrov** [comment]
I will think about it, it may be hard to implement, though I have some doubts about necessity of this feature.

**Comment by artyompetrov** [comment]
Examples are displayed near the corresponding definitions. It is impossible to move them to another field unless Addon starts to create individual cards for every part of speech. And I don't want to do that because If I start to create individual cards for every part of speech, those cards will be shown as duplicates.
